title: Goal Toolkit
baseurl: https://colegion.github.io/goal

menu:
  about:
    name: About
    url: /
    icon: sun
  manual:
    name: Manual
    url: /manual/index.html
    icon: book
  tracker:
    name: Issue Tracker
    uri: https://github.com/colegion/goal/issues
    icon: bug

manual:
  -
    name: Introduction
    url: /manual/index.html
    icon: file text
    category: manual
    pages:
      -
        name: Getting Started
        local: true
  -
    name: goal new
    url: /manual/new/index.html
    icon: cube
    category: new
    pages:
      -
        name: Default Layout
        local: true
  -
    name: goal run
    url: /manual/run/index.html
    icon: cube
    category: run
    pages:
      -
        name: Configuration file
        local: true
  -
    name: goal generate handlers
    url: /manual/handlers/index.html
    icon: cube
    category: handlers
    pages:
      -
        name: Controllers
        url: /manual/handlers/controllers.html
      -
        name: Actions
        url: /manual/handlers/actions.html
      -
        name: Routes
        url: /manual/handlers/routes.html
  -
    name: Standard controllers
    url: /manual/controllers.html
    icon: file text
    category: controllers
    pages:
      -
        name: Templates
        local: true
      -
        name: Requests
        local: true
  -
    name: Deployment
    url: /manual/deployment.html
    icon: file text

safe: true
lsi: false
markdown: redcarpet
highligher: pygments
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - with_toc_data
    - emphasis
    - double_emphasis
    - quote
